# Generated by Django 5.2.1 on 2025-06-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='category',
            field=models.CharField(blank=True, choices=[('health', 'Health/Fitness'), ('productivity', 'Productivity'), ('selfcare', 'Self-Care'), ('learning', 'Learning'), ('work', 'Work'), ('fun', 'Hobbies/Fun')], max_length=50),
        ),
    ]
