# Generated by Django 5.2.1 on 2025-06-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_remove_challenge_badge_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='required_habits',
            field=models.ManyToManyField(blank=True, to='habits.habit'),
        ),
    ]
