# Generated by Django 5.2.1 on 2025-06-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_challenge_required_habits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='challenge',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='required_habits',
            field=models.ManyToManyField(related_name='challenges', to='habits.habit'),
        ),
    ]
