# Generated by Django 5.2.1 on 2025-06-15 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_remove_challenge_badge_remove_challenge_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='icon',
        ),
        migrations.AddField(
            model_name='challenge',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.badge'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='required_habits',
            field=models.ManyToManyField(blank=True, to='habits.habit'),
        ),
    ]
