# Generated by Django 5.2.1 on 2025-06-15 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_remove_challenge_icon_challenge_badge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='challenge',
            name='auto_add_habits',
            field=models.BooleanField(default=False, help_text='Automatically add required habits to users who join'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='badge_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='badge_emoji',
            field=models.CharField(default='🏆', max_length=10),
        ),
        migrations.AddField(
            model_name='challenge',
            name='badge_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.challenge'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='description',
            field=models.TextField(blank=True, default='Completed a community challenge'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='emoji',
            field=models.CharField(default='🏆', max_length=10),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='title',
            field=models.CharField(default='Challenge Badge', max_length=100),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='required_habits',
            field=models.ManyToManyField(blank=True, related_name='challenge_requirements', to='habits.habit'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge', 'challenge')},
        ),
    ]
