# Generated by Django 5.2.1 on 2025-06-15 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_alter_userbadge_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='auto_add_habits',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='badge_description',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='badge_emoji',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='badge_title',
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
        migrations.AlterField(
            model_name='challenge',
            name='required_habits',
            field=models.ManyToManyField(blank=True, to='habits.habit'),
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='title',
        ),
    ]
