# Generated by Django 5.2.1 on 2025-06-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0012_remove_challenge_auto_add_habits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='emoji',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
