# Generated by Django 5.2.1 on 2025-06-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0013_badge_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='is_active',
        ),
        migrations.AddField(
            model_name='challenge',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='required_habits',
            field=models.ManyToManyField(related_name='challenges', to='habits.habit'),
        ),
    ]
