# Generated by Django 5.2.1 on 2025-06-15 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0014_remove_badge_emoji_remove_challenge_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='badge',
            field=models.ForeignKey(blank=True, help_text='Badge awarded upon completing this challenge', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.badge'),
        ),
    ]
